pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      sudo npm install -g n
      sudo n 19.9.0
      node -v
      npm -v
    displayName: 'Install Node.js 19.9 via script'

  - script: |
      node -v
      npm -v
    displayName: 'Check Node and NPM versions'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run build
    displayName: 'Build Nuxt app'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/_Staging2/drop/nuxt-app.zip'
    displayName: 'Archive Nuxt app'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/_Staging2/drop/nuxt-app.zip'
      artifactName: 'drop'
    displayName: 'Publish Build Artifacts'

